jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - checkout: self

      - task: DotNetCoreCLI@2
        inputs:
          displayName: "Restore"
          command: 'restore'
          projects: '**/*.csproj'
          feedsToUse: 'select'

      - task: DotNetCoreCLI@2
        displayName: Build all the Projects in the solution
        inputs:
          command: 'build'
          projects: '**/*.csproj'
          arguments: '--configuration release --no-restore'
      
